function TCPage() {
    return (
        <div className="bg-tertiary text-left px-16 py-8">
            <h1 className="text-3xl font-bold mb-4">Terms and Conditions</h1>
            <p className="mb-6">Welcome to Train Rex! These Terms of Use (“Terms”) are a contract between you and Train Rex (“Train Rex” or “we”) and govern your access to and use of any Train Rex mobile application (such as for iPhone or Android) or content (the “Platform”) or any fitness, recreational, wellness, or other experiences, activities, events, services, recordings, and/or products made available through Train Rex (collectively, “Services”). Please read these Terms carefully before accessing and using the Platform or Services.</p>

            <h3 className="text-2xl font-semibold mb-2">Terms</h3>
            <p className="mb-6">
                <span className="font-semibold">a) Acceptance of Terms.</span> By accessing and/or using the Platform and/or Services, or clicking any button to indicate your consent, you accept and agree to be bound by these Terms, just as if you had agreed to these Terms in writing. If you do not agree to these Terms, do not use the Platform or any Services. <br/><br/>
                <span className="font-semibold">b) Amendment of Terms.</span> Train Rex may amend the Terms from time to time. Unless we provide a delayed effective date, all amendments will be effective upon posting of such updated Terms. Your continued access to or use of the Platform or Services after such posting constitutes your consent to be bound by the Terms, as amended. <br/><br/>
                <span className="font-semibold">c) Additional Terms.</span> In addition to these Terms, certain plans, offers, products, services, elements or features may also be subject to additional terms, conditions guidelines or rules which may be posted, communicated or modified by us or the applicable third parties at any time. Your use of any such plan, offer, product, service, element or feature is subject to those additional terms and conditions, which are hereby incorporated by reference into the Terms, provided that in the event of any conflict between such additional terms and the Terms, the Terms shall control. The Train Rex is hereby incorporated by reference.
            </p>

            <h3 className="text-2xl font-semibold mb-2">Train Rex Platform</h3>
            <p className="mb-6">
                <span className="font-semibold">a) Train Rex Platform:</span> The Train Rex platform enables consumers to purchase a monthly subscription to [*]. <br/><br/>
                <span className="font-semibold">b) Membership Options:</span> There are a number of ways to participate in Train Rex, such as various subscription plans. These options consist of different subscription packages, services and features and may be subject to additional and differing conditions, prices, policies and limitations. We reserve the right to modify, terminate or otherwise amend our offered options and plans at any time in our discretion. Train Rex makes no commitment on the quantity, availability, type or frequency at which such Services, services, content and features will be available to non-subscribers and may modify, discontinue, remove or suspend access at any time and for any reason in our sole discretion. <br/><br/>
                <span className="font-semibold">c) Subscription Plans:</span> To enjoy full access to the Platform and Services, you need to sign up for a subscription. A subscription starts on the date that you sign up for a subscription and submit payment via a valid Payment Method (defined below) or reactivate a pre-existing subscription. Unless we otherwise communicate a different time period to you at the time of sign up or otherwise (such as a multi-month commitment plan), each billing cycle is one month in length (a “Subscription Cycle”). Your Train Rex subscription automatically renews each month, and we will automatically bill the monthly subscription fee to your Payment Method each month, until your subscription is cancelled or terminated. You must provide us with a current, valid, accepted method of payment (“Payment Method”). We may update the accepted methods from time to time. If you add a subscription to your base subscription or if you upgrade or downgrade to a different subscription, all such subscriptions will be governed by these Terms and will continue indefinitely until cancelled or terminated.<br/><br/>
                <span className="font-semibold">d) Use of Allocated Services:</span> Depending on the subscription plan you choose and purchase, you will be allotted Services to be used solely to book Services each Subscription Cycle. You can choose how you use your Services across the various Services available to you. Services expire at the end of each Subscription Cycle, meaning that any Services you don’t use during the applicable Subscription Cycle will not roll over into future months. You can find more information about the current rollover policies. You can see how many days you have left in each Subscription Cycle in your account settings. There will be no refund or payment for any unused amount. When your cycle automatically renews for the next month, you’ll automatically receive your new allotment of Services. If you have any questions about how to use your Services, please contact us and we can help you.<br/><br/> Services have no cash value or any other value outside of the Train Rex platform and are not redeemable for cash. For avoidance of doubt, the Services do not operate or serve as stored value facilities in any way. You may not transfer, trade, gift or otherwise exchange Train Rex Services.<br/><br/>
                <span className="font-semibold">e) Services Availability and Allocation:</span> The exact number and type of Services you get during any Subscription Cycle will depend on the subscription package you choose. Our partnered venues will allocate a chosen amount of time slots for the users of the Platform and Services, all allocated time slots and availability will be within booking page on the Train Rex app.<br/><br/> Train Rex does not guarantee the availability of particular venues, locations, services, experiences, content, inventory, spots or other features, and availability may change over time and at any time (including during the course of any given Subscription Cycle). The type, quantity, Services, allocation and availability of venues and other inventory offered, are determined by Train Rex in its sole discretion. Train Rex takes certain steps to release, promote and otherwise make available spots and inventory at varying times and in an ongoing and evolving way.<br/><br/>
                <span className="font-semibold">f) Non-Subscription Packages:</span> Train Rex has a free package that allows users access to  Train Rex AI chatbot. You acknowledge and agree that these Terms apply to any such purchase you make, and you will be responsible to pay the applicable fees, which may change at any time.<br/><br/>
                <span className="font-semibold">g) Use of Train Rex:</span> Your Train Rex account is personal to you and you agree not to create more than one account. You cannot transfer or gift Services to third parties or allow third parties to use your Train Rex account, including other Train Rex users. You must not use or exploit the Platform and/or Services for commercial purposes. To use your Train Rex membership you must have access to the Internet. We continually update and test various aspects of the Train Rex platform. We reserve the right to, and by using our Platform and/or Services you agree that we may, include you in or exclude you from these tests without notice. You understand and agree that Train Rex may take actions we deem reasonably necessary to prevent fraud and abuse.<br/><br/> You agree that the information you provide to Train Rex at sign up and at all other times will be true, accurate, current, and complete and that you will keep this information accurate and up-to-date at all times. When you sign up, you will be asked to create a password. You are solely responsible for all activity that occurs under your account, including any activity by unauthorized users. To use the Platform you must have access to the Internet and will be required to download a Train Rex mobile application to use Train Rex features. You are solely responsible for providing your own access (e.g., computer, mobile device, Internet connection, etc.) to the Platform and Services.<br/><br/>
                <span className="font-semibold">h) Eligibility Criteria:</span> The availability of all or part of our Platform and/or Services may be limited based on demographic, age, or other criteria as we may establish from time to time. You understand and agree that we may disallow you from subscribing to Train Rex or may terminate your subscription at any time based on these criteria. You further understand that the Platform and/or Services may not be available in every geography.<br/>
            </p>
            TRAIN REX CURRENTLY OPERATES IN THE UNITED KINGDOM AND INDIA, ACCESS TO OUR PLATFORM IS NOT PERMITTED FROM OTHER JURISDICTIONS. THESE TERMS ARE ONLY APPLICABLE TO USERS IN THE UK AND INDIA. THE PLATFORM IS NOT AVAILABLE TO ANY USERS SUSPENDED OR REMOVED FROM THE PLATFORM BY TRAIN REX. BY USING THE PLATFORM, YOU REPRESENT THAT YOU ARE AT LEAST 18 YEARS OLD AND HAVE NOT BEEN PREVIOUSLY SUSPENDED OR REMOVED. THOSE WHO CHOOSE TO ACCESS THE PLATFORM DO SO AT THEIR OWN INITIATIVE AND ARE RESPONSIBLE FOR COMPLIANCE WITH ALL LOCAL RULES INCLUDING, WITHOUT LIMITATION, RULES ABOUT THE INTERNET, DATA, EMAIL OR OTHER ELECTRONIC MESSAGES, OR PRIVACY.<br/><br/>
            
            <h3 className="text-2xl font-semibold mb-2">Fees, Billing, Cancellation</h3>
            <p className="mb-6">
                <span className="font-semibold">a) Recurring Billing:</span> By initiating your Train Rex subscription, you authorize us to charge you for your initial subscription period and a recurring monthly subscription fee at the then current rate. Increases in the current rate will be notified to you by e-mail or other notice (such as when you log into your account). You acknowledge that the amount billed each month may vary for reasons that may include differing amounts due to promotional offers and/or changing or adding a plan, and you authorize us to charge your Payment Method for such varying amounts, which may be billed monthly in one or more charges. You also authorize us to charge you any other fees you may incur in connection with your use of the Platform, such as any applicable sign-up fee, taxes or cancellation or late fees, as further explained below. Note that even if you do not use the subscription or access the Platform and/or Services, you will be responsible for subscription fees until you cancel your subscription, or it is otherwise terminated.<br/><br/>
                <span className="font-semibold">b) Subscription Cycle:</span> When you sign up and purchase your Train Rex membership, your first Subscription Cycle will be billed immediately. Unless we expressly communicated otherwise, your subscription will automatically renew each month and you will be billed on the same date each month (being the date on which you signed up), provided that, where such date does not exist in particular renewal month, your subscription will be deemed to auto-renew on the day immediately following the date of expiry of your current membership cycle. All membership auto-renews will continue to take place on the new auto-renew date (i.e., in this example, the 1st of each month). Payment will be taken on the effective date of your auto-renew (a “Renewal Date”), provided that, if we are unable for any reason to take payment on a Renewal Date, we will take payment as soon as practically possible thereafter.<br/><br/>
                <span className="font-semibold">c) Refunds:</span> Our fees (including the monthly fee for your membership and any other fees) are non-refundable, unless we specifically communicate otherwise at the time of purchase.<br/><br/>
                <span className="font-semibold">d) Payment Methods:</span> You may edit your Payment Method information by logging onto our mobile app and editing it in your account settings. If a payment is not successfully settled, due to expiration, insufficient funds or otherwise, you nonetheless will remain responsible for any uncollected amounts and authorize us to continue billing the Payment Method or any other payment method you have provided, as it may be updated, including in the event you attempt to create a new account, reactivate the unsettled account or sign up for a new account. This may result in a change to your payment billing dates. If we cannot charge your account, we reserve the right, but are not obligated, to terminate your access to our Platform or any portion thereof.<br/><br/>
                <span className="font-semibold">e) Price Changes:</span> We reserve the right to adjust pricing at any time. Unless we expressly communicated otherwise, any price changes to your subscription will take effect on your next billing cycle upon notice communicated through a posting on the Train Rex mobile app or such other means as we may deem appropriate from time to time, such as email. If you do not cancel your subscription, you will be deemed to have accepted these new fees.<br/><br/>
                <span className="font-semibold">f) Cancellation:</span> Unless we communicate otherwise, you may terminate your subscription at any time before your subscription renews, by going into your account settings on the Train Rex platform and letting us know you would like to cancel. Unless we communicate otherwise, following any cancellation you will continue to have access to your subscription through the end of your current prepaid Subscription Cycle, unless you cancel and receive a refund, in which case your access will be terminated immediately. Note that if you do terminate your subscription, we reserve the right to charge a reactivation fee if you want to return to Train Rex in future months or to restrict your access in future months.<br/><br/>
                <span className="font-semibold">g) Fees Charged by Venues:</span> In addition to the fees we charge, the gym venues may also charge equipment or other amenity fees that you will be responsible for directly. For example, some gym venues might charge extra to use pool, sauna or other facilities that can be found in the chargeable extra tab within the gym profile page. Further, Train Rex only gives you access to the gyms for which you signed up on the Platform (and at the specified time and location). The venue may have additional fees for use of additional facilities.<br/><br/>
                <span className="font-semibold">h) Third Party Fees for Using Train Rex:</span> You are also responsible for all third-party charges and fees associated with connecting to and using the platform and/or Services, including fees such as internet service provider fees, telephone and computer equipment charges, sales tax and any other fees necessary to access the Platform and/or Services.<br/>
            </p>

            <h3 className="text-2xl font-semibold mb-2">Promotions</h3>
            <p className="mb-6">
                <span className="font-semibold">a) Trials:</span> From time to time we may offer a trial membership that includes access to the Train Rex platform during the trial period. Trials will have the duration and price communicated at the time you sign upEach trial membership automatically will convert to a regular monthly subscription and price unless cancelled before the last day of trial. Customers that cancel and do not convert to a regular subscription may not attend Services taking place after the end of the trial membership period (even if booking occurred before the end of the applicable trial period). Trials, discount offers, and promotions (collectively “Trials”) may be redeemed as described in the specifics of the promotion and may be subject to additional or different terms. Unless we expressly communicate otherwise, Trials are not transferable, may not be combined with other offers or redeemed for cash and are void where prohibited. You understand and agree that unless we expressly communicated otherwise, Trials are available only to new users that have never had a Train Rex account before and there is only one Trial permitted per credit card or payment method and it is a violation of these Terms to sign up for a Trial if you have signed up for an account or trial in the past or to have more than one account or trial at the same time. Train Rex reserves the right, in its absolute discretion, to determine your eligibility for a Trial. If in our discretion we believe you are not eligible for a Trial, we reserve the right to prevent you from signing up for a Trial or to terminate your promotional subscription. If we terminate your Trials because you have violated these Terms, you understand that you will not be eligible for a refund.<br/><br/>
                <span className="font-semibold">b) Refer a Friend:</span> From time to time we may make available certain incentives for Train Rex users to refer a friend to use Train Rex. The current terms that apply to referrals can be found.<br/><br/>
                <span className="font-semibold">c) Other Promotions:</span> Train Rex may offer additional types of offers and promotions which will be subject to additional terms and conditions that Train Rex may provide.<br/>
            </p>

            <h3 className="text-2xl font-semibold mb-2">Termination or Modification by Train Rex</h3>
            <p className="mb-6">
                You agree that Train Rex, in its sole discretion and for any or no reason at any time, may (i) terminate, cancel, deactivate, disable, delete and/or suspend any account, subscription, any orders placed, your access to or use of the Platform, your membership and/or Services (or any part thereof) you may have with Train Rex or use of the Platform and remove and discard all or any part of your account or any content uploaded by you and/or (2) discontinue, disable, suspend, modify or alter any aspect, feature or policy of the Platform including of your subscription. Train Rex may also in its sole discretion and at any time discontinue providing access to the Platform, or any part thereof, with or without notice. You agree that any termination of your access to the Platform or any account you may have or portion thereof may be effected without prior notice. This includes the right to terminate or modify any subscription prior to the end of any pre-paid or committed period. Upon any termination or otherwise, we may immediately deactivate your account and all related information and/or bar any further access to your account information and the Platform. Train Rex shall have no liability for, and you shall have no recourse for, any such termination or deactivation, except as set forth in the following sentence. You agree that Train Rex will not be liable to you or any third party for any such termination.<br/>
            </p>

            <h3 className="text-2xl font-semibold mb-2">Privacy</h3>
            <p className="mb-6">
                Your privacy is important to Train Rex. The Train Rex Privacy Policy is hereby incorporated into these Terms by reference. Please read the privacy policy carefully for information relating to Train Rex’s collection, use, and disclosure of your personal information.<br/>
            </p>

            <h3 className="text-2xl font-semibold mb-2">Prohibited Conduct</h3>
            <p>
                Without limiting the prohibitions and restrictions found elsewhere throughout the Terms, you agree not to:
            </p>
            <ul className="list-disc ml-8 mb-4">
                <li>Harass, threaten, stalk, disrupt or defraud users, members or staff of Train Rex or any other person, or otherwise create or contribute to an unsafe, harassing, threatening or disruptive environment;</li>
                <li>Act in a deceptive or fraudulent manner by, among other things, impersonating another person or access another user’s account without that person’s permission;</li>
                <li>Share Train Rex passwords with any third party or encourage any other user to do so;</li>
                <li>Permit anyone to use any Services booked under your own membership, including other members;</li>
                <li>Reproduce, modify, prepare derivative works based upon, distribute, license, lease, sell, resell, transfer, publicly display, publicly perform, transmit, stream, broadcast, use for commercial purposes or otherwise exploit any portion of the Platform;</li>
                <li>Misrepresent the source, identity, or content of information transmitted via the Platform, including deleting the copyright or other proprietary rights or notices from any portion of the Platform;</li>
                <li>Upload material (e.g. virus) that is damaging to computer systems or data of Train Rex or users of the Platform or otherwise use the Platform in any manner that could damage, disable, overburden, or impair it or interfere with any other party’s use and enjoyment of the Platform;</li>
                <li>Upload copyrighted material that is not your own or that you do not have the legal right to distribute, display, and otherwise make available to others;</li>
                <li>Upload or send to Platform users pornographic, threatening, embarrassing, hateful, racially or ethnically insulting, libelous, or otherwise inappropriate content;</li>
                <li>Decompile, reverse engineer or disassemble the Platform, in whole or in part, except as may be permitted by applicable law;</li>
                <li>Link to, mirror or frame any portion of the Platform;</li>
                <li>Cause or launch any program or scripts for the purpose of scraping, indexing, surveying, or otherwise data mining any portion of the Platform or unduly burdening or hindering the operation and/or functionality of any aspect of the Platform;</li>
                <li>Attempt to gain unauthorized access to or impair any aspect of the Platform or its related systems or networks or interfere or attempt to interfere with the proper working of the Platform or any activities conducted on the Platform;</li>
                <li>Make unsolicited offers, advertisements, proposals, or send junk mail or “spam” to users;</li>
                <li>Remove, circumvent, disable, damage or otherwise interfere with security-related features of the Platform, any features that prevent or restrict use or copying of any content accessible through the Platform, or any features that enforce limitations on the use of the Platform or the content therein;</li>
                <li>Obtain or attempt to obtain any materials or information through any means not intentionally made available through the Platform;</li>
                <li>Modify the Platform in any manner or form, nor to use modified versions of the Platform, including (without limitation) for the purpose of obtaining unauthorized access to the Platform;</li>
                <li>Use any robot, spider, scraper, or other automated means to access the Platform for any purpose without our express written permission or bypass our robot exclusion headers or other measures we may use to prevent or restrict access to the Platform;</li>
                <li>Use the Platform for or in connection with any purpose that is unlawful or prohibited by these Terms.</li>
            </ul>
            <p>
                Train Rex reserves the right to refuse service, terminate accounts, remove or edit content, or cancel orders in its sole discretion.<br/><br/>
            </p>

            <h3 className="text-2xl font-semibold mb-2">User Submissions</h3>
            <p className="mb-6">
                <span className="font-semibold">a) General:</span> The Platform provides certain features which enable you and other users to submit, post, and share content, which may include without limitation text, graphic, pictorial and video works, or any other content submitted by you and other users through the Platform (“User Submissions”). Train Rex does not guarantee any anonymity or confidentiality with respect to any User Submissions, and strongly recommends that you think carefully about what you upload to, share with or make accessible to the Platform. You understand and agree that User Submissions may be made public without any additional notice to or consent by you and you should assume that any person (whether or not a user of Train Rex’ platform), may read or have access to your User Submissions. Train Rex is not responsible for the use or disclosure of any information that you disclose in connection with User Submissions, including any personal information. User Submissions are displayed for information purposes only and reflect the opinions of the person making the submission. They are not controlled by, and may not reflect the opinion of, Train Rex. You understand that all User Submissions are the sole responsibility of the person from whom such User Submission originated. This means that you, and not Train Rex, are entirely responsible for all User Submissions that you upload, post, e-mail, transmit, or otherwise make available through the Platform.<br/><br/>
                <span className="font-semibold">b) Right to Remove or Edit User Submissions:</span> Train Rex makes no representations that it will publish or make available on the Platform any User Submissions, and reserves the right, in its sole discretion, to refuse to allow any User Submissions on the Platform, or to edit or remove any User Submission at any time with or without notice. Train Rex may, but is not obligated to, monitor and edit or remove any activity or content, in whole or in part, including but not limited to content that Train Rex determines in its sole discretion to violate the standards of this Platform. Train Rex takes no responsibility and assumes no liability for any User Submissions.<br/><br/>
                <span className="font-semibold">c) License Grant by You to Train Rex:</span> You retain all of your ownership rights in original aspects of your User Submissions. By submitting User Submissions to Train Rex, you hereby grant Train Rex and its affiliates, sublicensees, partners, designees, and assignees of the Platform (collectively, the “Train Rex Licensees”) a worldwide, non-exclusive, fully paid-up, royalty-free, perpetual, irrevocable, sublicensable, and transferable license to use, reproduce (including by making mechanical reproductions), distribute, modify, adapt, translate, prepare derivative works of, publicly display, publish, publicly perform, and otherwise exploit your User Submissions and derivatives thereof in connection with the Platform and Train Rex’s (and its successors’) business for any purpose, including, without limitation, for marketing, promoting, and redistributing part or all of the Platform (and derivative works thereof), in any media formats and through any media channels now known or hereafter discovered or developed.<br/><br/>
                <span className="font-semibold">d) User Submissions Representations and Warranties:</span> You are solely responsible for your own User Submissions and the consequences of posting, sharing, displaying, publishing them or otherwise making them available. In connection with User Submissions, you affirm, represent, and warrant that: (i) you own, or have the necessary licenses, rights, consents, and permissions to use and authorize Train Rex to use all patent, trademark, copyright, or other proprietary rights in and to your User Submissions to enable inclusion and use of your User Submissions in the manner contemplated by Train Rex and these Terms, and to grant the rights and license set forth above, and (ii) your User Submissions, Train Rex’s or any Train Rex Licensee’s use of such User Submissions pursuant to these Terms, and Train Rex’s or any of Train Rex Licensee’s exercise of the license rights set forth above, do not and will not: (a) infringe, violate, or misappropriate any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; (b) contain any material that is illegal, threatening, obscene, racist, defamatory, libelous, hateful, pornographic, purposely false or otherwise injurious to third parties, promotional in nature, promotes any illegal activity or harm to groups or individuals, or consists of or contain software, computer viruses, commercial solicitation, political campaigning, chain letters, mass mailings, any form of “spam” or references to illegal activity, malpractice or false advertising; (c) violate these Terms or any applicable law or regulation, or these Terms ; or (d) exploits minors or (e) require obtaining a license from or paying fees or royalties to any third party for the exercise of any rights granted in these Terms, including, by way of example and not limitation, the payment of any royalties to any copyright owners, including any royalties to any agency, collection society, or other entity that administers such rights on behalf of others.<br/><br/>
                <span className="font-semibold">e) Inaccurate or Offensive User Submissions:</span> You understand that when using the Platform, you may be exposed to User Submissions from a variety of sources and that Train Rex does not endorse and is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such User Submissions. You further understand and acknowledge that you may be exposed to User Submissions that are inaccurate, offensive, indecent, or objectionable. YOU ACKNOWLEDGE AND AGREE, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THAT NEITHER TRAIN REX HAS ANY LIABILITY TO YOU IN RESPECT OF ANY SUCH USER SUBMISSIONS.<br/><br/>
                <span className="font-semibold">f) Feedback:</span> If you provide Train Rex with any comments, bug reports, feedback, or modifications proposed or suggested by you to the Platform (“Feedback”), Train Rex shall have the right to use such Feedback at its discretion, including, but not limited to the incorporation of such suggested changes into the Platform. You hereby grant Train Rex a perpetual, irrevocable, nonexclusive license under all rights necessary to incorporate and use your Feedback for any purpose without notice to, consent by or compensation to you or any third party.<br/><br/>
                <span className="font-semibold">g) Infringing or Illegal Activity:</span> In the event of infringing or other illegal activities, we have no obligation to, but reserve the right to terminate access to the Platform and remove all content submitted by any persons who are found to be infringers. Any suspected illegal activity may be referred to appropriate law enforcement authorities. These remedies are in addition to any other remedies Train Rex may have at law or in equity.<br/>
            </p>
            
            <h3 className="text-2xl font-semibold mb-2">Ownership; Proprietary Rights</h3>
            <p className="mb-6">
                The Train Rex mobile applications are owned and operated by the Train Rex Company. The content, recordings, visual interfaces, graphics, design, compilation, information, computer code, products, software (including any downloadable software), services, and all other elements of the Platform provided by Train Rex (“Materials”) are protected by local copyright, trade dress, patent, and trademark laws, international conventions, and all other relevant intellectual property and proprietary rights, and applicable laws. Except for your User Submissions, all Materials contained on the Platform are the copyrighted property of Train Rex or its subsidiaries or affiliated companies and/or third-party licensors whether registered or unregistered and may not be used in connection with any product or service or in any manner that is likely to cause confusion as to our endorsement, affiliation or sponsorship of any person, product or service.. All trademarks, service marks, and trade names used by us on the Platform are proprietary to Train Rex or its affiliates and/or third-party licensors. Except as expressly authorized by Train Rex, you agree not to sell, license, distribute, copy, modify, publicly perform or display, transmit, publish, edit, adapt, create derivative works from, or otherwise make unauthorized use of the Materials and may only access the Materials for your personal, non-commercial use. In the event that Materials are downloaded to your computer or mobile phone, you do not obtain any ownership interest in such Materials. All rights not expressly granted in this Agreement are reserved.
            </p>

            <h3 className="text-2xl font-semibold mb-2">Third-party Platforms, Products and Services; Links</h3>
            <p className="mb-6">
                The Platform may include links to other platforms or services (“Linked Platforms”) solely as a convenience to users. Train Rex does not endorse any such Linked Platforms or the information, material, products, or services contained on other linked platforms or accessible through other Linked Platforms. Furthermore, Train Rex makes no express or implied warranties with regard to the information, material, products, or services that are contained on or accessible through linked Platforms. ACCESS AND USE OF LINKED PLATFORM, INCLUDING THE INFORMATION, MATERIAL, PRODUCTS, AND SERVICES ON LINKED PLATFORM OR AVAILABLE THROUGH LINKED PLATFORM, IS SOLELY AT YOUR OWN RISK.<br/><br/> 
                Sometimes promotional plans are offered in conjunction with the provision of third party products and services. We are not responsible for the products and services provided by such third parties, and use of such products and services is at your own risk.<br/><br/>
                Your correspondence or business dealings with, or participation in promotions of, third parties found on or through the Platform are solely between you and such third party. YOU AGREE THAT TRAIN REX WILL NOT BE RESPONSIBLE OR LIABLE FOR ANY LOSS OR DAMAGE OF ANY SORT INCURRED AS THE RESULT OF ANY SUCH DEALINGS OR AS THE RESULT OF THE PRESENCE OF SUCH THIRD PARTY ON THE PLATFORM.
            </p>

            <h3 className="text-2xl font-semibold mb-2">DISCLAIMERS</h3>
            <p className="mb-6">
                SERVICES AND ANY OTHER PRODUCTS AND SERVICES MADE AVAILABLE VIA THE PLATFORM ARE PROVIDED BY THIRD PARTIES (AND THE DESCRIPTIONS OF THE FOREGOING POSTED ON THE PLATFORM ARE PROVIDED BY SUCH THIRD PARTIES), NOT TRAIN REX. YOU AGREE THAT YOUR USE OF THE PLATFORM AND ATTENDANCE AT, PARTICIPATION IN, PURCHASE AND/OR USE OF ANY SERVICES IS SOLELY AT YOUR OWN RISK. WE DO NOT ASSUME ANY LIABILITY OR MAKE ANY WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, ARISING OUT OF, IN CONNECTION WITH OR WITH RESPECT TO THE PLATFORM AND/OR SERVICES.<br/><br/>
                IN NO EVENT SHALL TRAIN REX BE LIABLE FOR ANY INJURY, LOSS, CLAIM, DAMAGE OR ANY SPECIAL, EXEMPLARY, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL DAMAGES OF ANY KIND, WHETHER BASED IN CONTRACT, TORT OR OTHERWISE, WHICH ARISES OUT OF OR IS ANY WAY CONNECTED WITH A USER’S ATTENDANCE, USE OF OR PARTICIPATION IN A CLASS, OR PRODUCT, OR THE PERFORMANCE OR NON-PERFORMANCE OF ANY THIRD PARTY. TRAIN REX PROVIDES ACCESS TO STUDIOS' SERVICES. TRAIN REX IS NOT OTHERWISE CONNECTED TO, NOR IS AN AGENT OF ANY THIRD PARTY WITH WHICH A USER HAS MADE A RESERVATION. WITHOUT LIMITING ANYTHING HEREIN, TRAIN REX DISCLAIMS ALL WARRANTIES, WHETHER STATUTORY, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, RELATED TO ANY SERVICES, ACTIVITIES, OR OTHER SERVICES OFFERED BY STUDIOS VIA THE PLATFORM.<br/><br/>
                UNLESS OTHERWISE EXPRESSLY STATED BY TRAIN REX, ALL ASPECTS OF OR CONTENT OR FEATURES MADE AVAILABLE THROUGH THE PLATFORM AND/OR SERVICES ARE PROVIDED “AS IS” AND “AS AVAILABLE” WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, TRAIN REX, ITS SUPPLIERS AND PARTNERS DISCLAIM ALL WARRANTIES, STATUTORY, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS.<br/><br/>
                UNLESS OTHERWISE EXPRESSLY STATED BY TRAIN REX, TRAIN REX, ITS SUPPLIERS AND PARTNERS DO NOT WARRANT OR MAKE ANY REPRESENTATIONS (I) THAT THE PLATFORM AND /OR ANY CLASSES SUITABLE FOR YOU OR WILL MEET YOUR PERSONAL NEEDS, (II) REGARDING THE ADEQUACY OR SAFETY OF ANY CLASS OR RECOMMENDATION, (III) THAT THE PLATFORM AND/OR ANY CLASS, OR ANY ASPECT THEREOF,WILL BE AVAILABLE OR PERMITTED IN YOUR JURISDICTION, (IV) THAT THE PLATFORM, OR ANY ASPECT THEREOF WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE PLATFORM AND ANY DOWNLOADABLE SOFTWARE, CONTENT, SERVICES, OR APPLICATIONS MADE AVAILABLE IN CONJUNCTION WITH OR THROUGH THE PLATFORM OR THE SERVER THAT MAKES THEM AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, OR (V) REGARDING THE USE OF THE PLATFORM AND ANY DOWNLOADABLE SOFTWARE, CONTENT, SERVICES, OR APPLICATIONS MADE AVAILABLE IN CONJUNCTION WITH OR THROUGH THE PLATFORM IN TERMS OF CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE. YOU UNDERSTAND AND AGREE ANY MATERIAL OR DATA THAT YOU DOWNLOAD OR OTHERWISE OBTAIN THROUGH THE USE OF THE PLATFORM IS AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY INJURY, LOSS OR DAMAGES, INCLUDING DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF SUCH MATERIAL OR DATA.<br/><br/>
            </p>

            <h3 className="text-2xl font-semibold mb-2">Waiver</h3>
            <p className="mb-6">
                YOU UNDERSTAND THAT TRAIN REX IS NOT A GYMNASIUM, PLACE OF AMUSEMENT OR RECREATION, HEALTH CLUB, FACILITY, FITNESS STUDIO OR SIMILAR ESTABLISHMENT AND THE SERVICES THEY PROVIDE ARE OPERATED AND DELIVERED BY THE APPLICABLE VENUE AND NOT BY TRAIN REX. TRAIN REX IS NOT RESPONSIBLE FOR THE QUALITY OF ANY GYM PROVIDED BY A VENUE OR THIRD PARTY (INCLUDING BUT NOT LIMITED TO THE FACILITY, INSTRUCTOR OR CURRICULUM). YOU ARE SOLELY RESPONSIBLE FOR DETERMINING WHETHER THE CLASS OR RECOMMENDATIONS AVAILABLE ON OR THROUGH THE PLATFORM AND/OR SERVICES ARE RIGHT FOR YOU.<br/><br/>
                YOU UNDERSTAND THAT THERE ARE CERTAIN INHERENT RISKS AND DANGERS IN EXERCISING AND THAT THE SERVICES YOU MAY ATTEND OR PARTICIPATE IN OFFER A RANGE OF ACTIVITY AND INTENSITY LEVELS. BY USING TRAIN REX (INCLUDING BUT NOT LIMITED TO ATTENDING, PARTICIPATING IN OR USING A CLASS), YOU ACKNOWLEDGE AND AGREE, ON BEHALF OF YOURSELF, YOUR HEIRS, PERSONAL REPRESENTATIVES AND/OR ASSIGNS THAT YOU ARE AWARE OF THESE RISKS WHICH INCLUDE, BUT ARE NOT LIMITED TO, PROPERTY DAMAGE, ILLNESS, LOSS AND BODILY INJURY OR DEATH. YOU ACKNOWLEDGE THAT SOME OF THESE RISKS CANNOT BE ELIMINATED AND YOU SPECIFICALLY ASSUME THE RISK OF INJURY OR HARM.<br/><br/>
                YOU ALSO UNDERSTAND AND AGREE THAT THE PLATFORM OFFERS FITNESS AND RELATED INFORMATION THAT IS DESIGNED FOR INFORMATIONAL, EDUCATIONAL AND ENTERTAINMENT PURPOSES ONLY. NOTHING STATED OR POSTED ON OR OTHERWISE AVAILABLE THROUGH ANY ASPECT OF THE PLATFORM AND/OR A CLASS IS INTENDED TO BE, AND MUST NOT BE TAKEN TO BE, THE PRACTICE OF MEDICAL, PROFESSIONAL OR COUNSELING CARE. YOU SHOULD NOT RELY ON ANY INFORMATION ON OR THROUGH THE PLATFORM AND/OR A CLASS AS A SUBSTITUTE FOR, NOR DOES IT REPLACE, PROFESSIONAL MEDICAL ADVICE, DIAGNOSIS, OR TREATMENT. IF YOU HAVE ANY CONCERNS OR QUESTIONS ABOUT YOUR HEALTH OR FITNESS LEVEL, YOU SHOULD ALWAYS CONSULT A PHYSICIAN OR OTHER HEALTH-CARE PROFESSIONAL. DO NOT EVER DISREGARD, AVOID OR DELAY OBTAINING MEDICAL OR HEALTH RELATED ADVICE FROM YOUR HEALTH-CARE PROFESSIONAL BECAUSE OF SOMETHING YOU MAY HAVE READ OR HEARD ON OR THROUGH THE PLATFORM AND/OR A CLASS. THE USE OF ANY OF THE CONTENT, RECOMMENDATIONS AND INFORMATION PROVIDED ON OR THROUGH TRAIN REX IS SOLELY AT YOUR OWN RISK.<br/><br/>
                THE PLATFORM IS CONTINUALLY UNDER DEVELOPMENT AND TRAIN REX MAKES NO WARRANTY OF ANY KIND, IMPLIED OR EXPRESS, AS TO ITS ACCURACY, COMPLETENESS OR APPROPRIATENESS FOR ANY PURPOSE. IN THAT REGARD, DEVELOPMENTS IN RESEARCH MAY IMPACT THE FITNESS OR RELATED ADVICE THAT APPEARS ON OR IN CONNECTION WITH THE PLATFORM. NO ASSURANCE CAN BE GIVEN THAT THE ADVICE OR RECOMMENDATIONS CONTAINED IN OR THROUGH THE PLATFORM AND/OR A CLASS WILL ALWAYS INCLUDE THE MOST RECENT FINDINGS OR DEVELOPMENTS WITH RESPECT TO THE PARTICULAR MATERIAL.<br/><br/>
                THEREFORE, TO THE FULLEST EXTENT PERMITTED BY LAW, YOU RELEASE, TRAIN REX, ITS PARENT, SUBSIDIARIES OR AFFILIATED ENTITIES, AND EACH OF THEIR RESPECTIVE OFFICERS, DIRECTORS, MEMBERS, EMPLOYEES, CONSULTANTS, CONTRACT EMPLOYEES, REPRESENTATIVES AND AGENTS, AND EACH OF THEIR RESPECTIVE SUCCESSORS AND ASSIGNS, FROM ANY AND ALL RESPONSIBILITY, CLAIMS, ACTIONS, SUITS, PROCEDURES, COSTS, EXPENSES, DAMAGES AND LIABILITIES ARISING OUT OF OR IN ANY WAY RELATED TO YOUR PARTICIPATION IN OR USE OF THE PLATFORM AND/OR ATTENDANCE AT, PARTICIPATION IN, PURCHASE OF AND/OR USE OF ANY CLASS) INCLUDING BUT NOT LIMITED TO WITH RESPECT TO BODILY INJURY, PHYSICAL HARM, LOSS, ILLNESS, DEATH OR PROPERTY DAMAGE.<br/>
            </p>

            <h3 className="text-2xl font-semibold mb-2">Limitation of Liability and Damages</h3>
            <p className="mb-6">
                NOTHING IN THESE TERMS (INCLUDING BUT NOT LIMITED TO THE “DISCLAIMERS” ABOVE AND LIMITATIONS OF LIABILITY BELOW) IS INTENDED TO EXCLUDE OR LIMIT ANY LIABILITY THAT WE MAY HAVE TO YOU BY OPERATION OF APPLICABLE LAW. THIS INCLUDES LIABILITY FOR DEATH OR PERSONAL INJURY ARISING FROM OUR NEGLIGENCE, OR OUR FRAUD OR FRAUDULENT MISREPRESENTATION. IT IS ACKNOWLEDGED HOWEVER, THAT WE ACCEPT NO LIABILITY FOR THE NEGLIGENCE OF THIRD PARTIES, INCLUDING ANY STUDIO WHERE YOU MAY REDEEM ELIGIBLE SERVICES.<br/><br/>
                UNDER NO CIRCUMSTANCES, INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE, WILL TRAIN REX OR ITS AFFILIATES, CONTRACTORS, EMPLOYEES, AGENTS, OR THIRD-PARTY PARTNERS OR SUPPLIERS BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES ARISING FROM OR RELATED TO THE USE OF THE PLATFORM, INCLUDING THOSE THAT RESULT FROM THE USE OR THE INABILITY TO USE THE MATERIALS ON THE PLATFORM, OR ANY OTHER INTERACTIONS WITH TRAIN REX, EVEN IF TRAIN REX OR A TRAIN REX AUTHORIZED REPRESENTATIVE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. APPLICABLE LAW MAY NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY OR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. IN SUCH CASES, TRAIN REX’S LIABILITY WILL BE LIMITED TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW.<br/>
            </p>

            <h3 className="text-2xl font-semibold mb-2">Venue Waivers and Terms</h3>
            <p className="mb-6">
                Members taking Services are deemed to agree to the liability waivers and terms of individual gym venues. Your participation in any class may be subject to addition policies, rules or conditions of the applicable gym venue and you understand and agree that you may not be permitted to reserve or attend Services or services if you do not comply with these Terms or the policies of the venues or as otherwise determined by a venue.
            </p>

            <h3 className="text-2xl font-semibold mb-2">Dispute Resolution</h3>
            <p className="mb-6">
                Generally, if a dispute arises between Train Rex and you, our goal is to provide you with a neutral and cost effective means of resolving the dispute quickly. Accordingly, you and Train Rex agree that the parties will resolve any claim or controversy at law or equity that arises out of this Agreement or the Platform (a “Claim”) in accordance with one of the subsections below or as you and we otherwise agree in writing. Before resorting to these alternatives, we strongly encourage you to first contact us directly to seek a resolution. We will consider reasonable requests to resolve the dispute through alternative dispute resolution procedures, such as mediation or arbitration, as alternatives to litigation.
            </p>

            <h3 className="text-2xl font-semibold mb-2">Miscellaneous</h3>
            <p className="mb-6">
                <span className="font-semibold">a) Choice of Law Forum:</span> These Terms shall be governed in all respects by the laws of India, without regard to conflict of law provisions. You agree that any claim or dispute you may have against Train Rex must be resolved by a court located in New Delhi, India except as otherwise agreed by the parties. You agree to submit to the personal jurisdiction of the courts located within India for the purpose of litigating all such claims or disputes.<br/><br/>
                <span className="font-semibold">b) Assignment:</span> We may assign our rights and obligations under these Terms. The Terms will inure to the benefit of our successors, assigns and licensees.<br/><br/>
                <span className="font-semibold">c) Severability:</span> If any provision of these Terms shall be unlawful, void, or for any reason unenforceable, then that provision will be deemed severable from these Terms and will not affect the validity and enforceability of any remaining provisions.<br/><br/>
                <span className="font-semibold">d) Headings:</span> The heading references herein are for convenience purposes only, do not constitute a part of these Terms, and will not be deemed to limit or affect any of the provisions hereof.<br/><br/>
                <span className="font-semibold">e) Entire Agreement:</span> This (including the documents referred to herein), as each may be amended as set forth herein, is the entire agreement between you and Train Rex relating to the subject matter herein.<br/><br/>
                <span className="font-semibold">f) Disclosures:</span> The services hereunder are offered by Train Rex company, a [*] <br/><br/>
                <span className="font-semibold">g) Waiver:</span> A provision of these Terms may be waived only by a written instrument executed by the party entitled to the benefit of such provision. The failure of any party at any time to require performance of any provision of these Terms will in no manner affect such party’s right at a later time to enforce the same. A waiver of any breach of any provision of these Terms will not be construed as a continuing waiver of other breaches of the same or other provisions of these Terms. Further, in the event we choose to grant an exception to these Terms, any such exception is in our sole discretion and does not entitle you or anyone else to any exceptions in the future for similar circumstances.<br/><br/>
                <span className="font-semibold">h) Notices:</span> Notices will be sent to you at the email address that you provided to Train Rex during the registration process. Notices may be sent to us. Notice will be deemed given 24 hours after email is sent, unless the sender receives an automatic, electronic notification that such notice was not successfully received. Without prejudice to the foregoing, we may serve you legal notice by post to the address provided during the registration process. In such case, notice will be deemed given three days after the date of posting.<br/><br/>
                <span className="font-semibold">i) </span> Train Rex reserves the right to take down any usernames to avoid social media squatters. Its in our interest to protect our partners registered brand by taking action against anyone impersonating an individual or company. <br/>
            </p>
        </div>
    );
}


export default TCPage;